# -*- coding: utf-8 -*-
"""8.3.21_Class_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yJ27HDfDC_WHkdoBxdVDt-cY8zdrwwk1
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

salaries_df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/Salaries.csv')

type(salaries_df)

salaries_df.shape

salaries_df.head()

salaries_df.head(7)

salaries_df.head(-7)

salaries_df.tail()

df.tail(-7)

df.describe()

df.mean()

df.median()

df.max()

df.min()

sns_df[['sex', 'salary']]

type(sns_df)

sns_df.groupby('sex')['salary'].count()

#Create a spreadsheet-style pivot table as a DataFrame.
#pd.pivot_table(sns_df, index=['sex', 'salary'])

"""----------------------------------------

Extra info
"""

my_series = pd.Series([7,17,27,37])

my_series

my_series.values

import pandas as pd 
my_series = pd.Series([7,17,27,37])
my_series.index

# Commented out IPython magic to ensure Python compatibility.
#import required libraries 
import matplotlib.pyplot as plt 
# %matplotlib inline

sns_df.hist()

del sns_df['Unnamed: 1']

final_sns_df= sns_df

final_sns_df.head()

final_sns_df.hist()

final_sns_df.plot()

final_sns_df.plot(kind='hist')

final_faithful_df.plot(x='sex', y= 'salary', kind = 'scatter')

"""end to extra info

-----------------------------------------
"""

#Finding Median Salary for all males 
sns_df.groupby('sex')['salary'].count.median()

#Finding Median salary for all females

#Comparing the Mean salary of Males and Females

#DATA WRANGLING - perform some basic transformations on the data 
#People who have 20 years of experience (Total:157)
#(Mean Salary: 122,520.66)

#Comparing the salaries of people who have 20+ exp vs those not

#People who have salary of greater than or equal to 200,000

#RENAME VALUES, SUBSET COLUMNS, ETC

#CREATE VISUALIZATIONS

#DRAW CONCLUSIONS 
#My findings are...
#I also discovered that...