# -*- coding: utf-8 -*-
"""Assignment_2.5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/PetvyLi/data_analytics_2/blob/main/Assignment_2_5.ipynb
"""

#Make a list of 5 or more usernames, including an admin account.  Imagine you are writing code that will welcome people to your application on login. Loop through the list and print your greeting.
#If the admin account logs in, give them a special greeting.  They’re the admin, after all!
#Other users can get the generic greeting
usernames = ["John23", "Sarah64", "Bob98", "James20", "Admin"]
for name in usernames: 
  if name=="Admin":
    print("Welcome Admin! Have a wonderful day :)", name)
  else:
    print("Welcome to the application.", name)


#Store numbers 1-10 in a list
#Loop through the list
#Use an if-elif-else chain inside your loop to print the ordinal ending for each number – for example – 1st, 2nd, 3rd … etc.
       
numbers=[1,2,3,4,5,6,7,8,9,10]
for x in numbers:
    if x==1:
        print(str(x)+"st")
    elif x==2:
        print(str(x)+ "nd")
    elif x==3:
        print(str(x)+ "rd")
    else:
        print(str(x)+ "th")