# -*- coding: utf-8 -*-
"""Assignment_2.6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/PetvyLi/data_analytics_2/blob/main/Assignment_2_6.ipynb
"""

#Create a simple dictionary that stores 2 variables, for example: first and last name.
name = {"first_name": "Petvy", "last_name": "Li"}

#Print out those variables stored in your previous dictionary. 
print(name["first_name"])
print(name["last_name"])

#Add a message to those variables on printing: for example: “Hello, firstname lastname!”
print("Hello, " + name["first_name"] + " " + name["last_name"])

#Create a dictionary that holds 2 key: value pairs:
#Look through your dictionary and print each pair,
measurements = {"height": " : 163 cm", "weight" : " : 120 lb"}
for key, value in measurements.items(): 
  print(key + value)

#Create a nested dictionary containing three dictionaries – these dictionaries could be anything (favorite pets, travel locations, etc.)
#Loop through the dictionaries and print a message for each.

people = {"Person A":{"Name": "John", "Age": 20, "Favorite food": "Pizza"},
          "Person B":{"Name": "Sally", "Age": 25, "Favorite food": "Mochi"},
          "Person C":{"Name": "Mike", "Age": 27, "Favorite food": "Chips"}}
for key, value in people.items():
  print("This is a person and their information:", key, value)