# -*- coding: utf-8 -*-
"""Assignment_2.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/PetvyLi/data_analytics_2/blob/main/Assignment_2_3.ipynb
"""

#Create a list of 5 of your favorite tv shows.  
tvshows= ["Jeopardy", "Wheel of Fortune", "Game of Thrones", "Breaking Bad", "Lost"]


#Print the list in its original order.
print(tvshows)

#Use the sorted() function to print the list in alphabetical order.  How is sorted() different from sort()?
print(sorted(tvshows))
#-sorted()  is in alphabetical order.


#Print out your original list.
tvshows= ["Jeopardy", "Wheel of Fortune", "Game of Thrones", "Breaking Bad", "Lost"]
print(tvshows)


#Used sorted() to print your list in reverse alphabetical order.
tvshows=["Jeopardy", "Wheel of Fortune", "Game of Thrones", "Breaking Bad", "Lost"]
tvshows.sort(reverse=True)
print(tvshows)

#Create a message indicating how many favorite TV shows you have – use the len() function.
print("I have", len(tvshows), "favorite shows!")