# -*- coding: utf-8 -*-
"""Petvy_Li_Unit3_NumPy_Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XCjR7SXNEPQCoWO62rqphrHsVSmvTyDP

# Unit 3 - Advanced Python - NumPy - Assignment #1

## 1. Environment Set up
"""

import numpy as np 
import pandas as pd

#Dataset from summer Olympic London, year 2012
np_olympic_country = np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_Silver = np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze = np.array([19,22,32,29,7,17,14])



"""## 2.	Find country with maximum gold"""

import numpy as np 
import pandas as pd

#Dataset from summer Olympic London, year 2012
np_olympic_country = np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_Silver = np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze = np.array([19,22,32,29,7,17,14])
highest = np.where(np_olympic_country_Gold== np.max(np_olympic_country_Gold))
print('Max number of gold medals',np.max(np_olympic_country_Gold ))

print('The country with Max number of gold medals is:',np_olympic_country[highest])

"""## 3.	Find countries with more than 20 gold medals"""

more_than_20_gold=np_olympic_country_Gold > 20

print(more_than_20_gold)

np_olympic_country_Gold[more_than_20_gold]

x = np.where(np_olympic_country_Gold >20)

print('the countries with more than 20 medals are:', np_olympic_country[x])