# -*- coding: utf-8 -*-
"""Unit3_Python_Advanced_Pandas_DataWrangling_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A9UGhRH7gqxQfvtjXbWNHaOua4dm59PJ

# Assignment 1 : Python Data Analysis using salaries dataset

# Data Exploration:  This should include summary statistics, means, medians, quartiles, or any other relevant information about the data set.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/Salaries.csv')

type(df)

# 397 rows = 397 employees
df.shape

df.head()

df.tail()

df.describe()

"""# Mean/median of all salaries"""

# Mean of all salaries
df.mean()

# Median of all salaries
df.median()

"""# Median salary between gender and/or rank(title) Etc...

Making a new Data Frame that only has the columns 'sex' and 'salary'
"""

df[['sex', 'salary']]





"""Finding the Median salary for all males"""

male_df = df[(df['sex'] == 'Male')]

male_df['salary'].median()





"""Finding the Median salary for all females"""

female_df = df[(df['sex'] == 'Female')]

female_df['salary'].median()







"""Comparing the Mean salary of Males and Females"""

male_df.mean()-female_df.mean()



# The difference between mean salaries of male and female is $14,088

"""# Data Wrangling – perform some basic transformations on the data

People who have 20 years of experience (Total: 157), (Mean Salary: 122,520.66)
"""

group=df.groupby("yrs.service")

group = df.loc[df['yrs.service'] == 20]
print(group)



"""Comparing the salaries of people who have 20+ years of experience vs less than 20 years of experience"""

group = df.loc[df['yrs.service'] > 20]
print(group)

group = df.loc[df['yrs.service'] < 20]

"""People who have salary of greater than or equal to 200,000"""

group=df.groupby("salary")

group = df.loc[df['salary'] >= 200000]
print(group)

"""Your Findings here...

# Rename values, subset columns, etc
"""

new_df = df.rename(columns={"rank":"Position", "discipline": "Area"})

new_df = df.rename(columns={"": "Number"})

"""# Create some simple visualizations showing some simple statistics"""

df.plot(x="yrs.service", y="salary", kind="bar")

df.groupby("sex").plot(x="sex", y="salary", kind="bar")

df.plot(x="yrs.since.phd", y="salary", kind="bar")

df.hist()

df.boxplot()

"""Your observations from the visuals: 

The box plot isn't much helpful. Years in service doesn't really affect how much money one get. Male makes more money than females.

# Draw some conclusions based on the data.  What did you discover?

Based on the analysis performed above, the conclusions are as follows:

Your Findings here...

Associate Professors make less than Professors. Years in service doesn't seem to affect salary that much. Females make less than males. 

I also discovered that the -

Females make less than males. Meaning that there's still sexism in the workplace. 

Your Findings here...
I need more data such as what major they teach to have a more accurate representation and knowledge of why the data is the way it is.
"""